### ISSUE TITLE
Member Loads 

### ISSUE THREAD

**Issue by ssippe** [iainsproat/SharpFE#9]
Is it possible to add uniform member loads as opposed to point loads on the nodes?

**Comment by iainsproat** [comment]
Thanks for your interest and query.
No, only point loads have been implemented so far.
Typically all FE software does pre-processing of distributed loads (line,
area, body/volume etc.) and resolves them to point loads before undertaking
the actual FE calculation with point loads alone.
A separate module in SharpFE would have to be created to undertake this
resolution.

**Comment by ssippe** [comment]
I might get a chance to implement this down the track. Do you have any recommending reading on the math involved? I started a discussion [here](http://engineering.stackexchange.com/questions/7837/is-it-possible-to-convert-uniform-loads-to-point-loads) but it haven't yet figured out how to calculate the moments.

**Comment by ssippe** [comment]
Would you be interested in some contracting work to implement this feature? Please contact me at ssippe at-symbol gmail dot-symbol com I can give you some more info privately.

**Comment by iainsproat** [comment]
@ssippe while I'd really like to help it's most likely that I won't have time for any active development for a long while.
What I will do is try to find some time over the next week to improve the documentation.  Particularly provide links to reference material used, the architecture of SharpFE and design decisions.
If you are looking for a C# finite element library for structural analysis with more features and under continuous active development, I'd highly recommend http://www.karamba3d.com/

**Comment by ssippe** [comment]
Thanks for the recommendation. Karamba3d requires Rhinoceros and they both need to be installed with licenses. The licensing is not so much of a problem (i.e. we are happy to pay for it) but the the ability to do an automated install to 1-n cloud servers is a requirement. In other software that is licensed in the manner, automated installs are not possible so Karamba may not fit our needs.

**Comment by pearswj** [comment]
Sam, I recommend you contact the Karamba3d team (info@karamba3d.com) as I
believe the use case you describe is possible.

**Comment by ssippe** [comment]
@pearswj I'll do that. Thanks

**Comment by ssippe** [comment]
In case anyone else is in the same situation, Karamba3d is not good for our situation. However, http://frame3dd.sourceforge.net/ seems promising.
